python 000_make_env.py --configuration z
python 001_merge_quad_slice.py --configuration z
python 001b_insert_markers.py --configuration z
python 002_insert_bpm_corr.py --configuration z
python 003_split_dipoles.py --configuration z
python 004_make_python.py --configuration z
python 005_gen_madx.py --configuration z
python 006_set_pref_model_integrators.py --configuration z
python 007_move_files.py --configuration z